### ISSUE TITLE
No response when searching the documentation

### ISSUE THREAD

**Issue by sbstnrss** [querqy/querqy-docs#25]
Hi all, 

currently searching the docs does not return results at all. I checked different browsers (Chrome, Firefox, Edge) and a colleague can reproduce the issue. I guess the response is pending and not timed out or so...  

<img width="963" alt="image" src="https://user-images.githubusercontent.com/74548034/152548956-e6fbe70f-0d70-4ff5-862b-7377e36ea202.png">

Best, 
Sebastian

**Comment by renekrie** [comment]
Thanks for reporting. Looks like a misconfiguration (output from browser console):

```Uncaught ReferenceError: Stemmer is not defined
    at Object.query (searchtools.js:158)
    at Object.setIndex (searchtools.js:98)
    at <anonymous>:1:8
    at b (jquery.js:2)
    at Function.globalEval (jquery.js:2)
    at text script (jquery.js:2)
    at jquery.js:2
    at l (jquery.js:2)
    at XMLHttpRequest.<anonymous> (jquery.js:2) ```

**Comment by epugh** [comment]
Oddly enough on my local test set up it all works fine....     Oh, and what the heck is `./docs/source/_static/js/custom.js`?   Looks like an idea that maybe didn't pan out?

**Comment by renekrie** [comment]
Thanks @sbstnrss. Could you try to put that into a pull request?

**Comment by sbstnrss** [comment]
Search is back to work now 👍
