### ISSUE TITLE
Broken link on https://docs.querqy.org/querqy/index.html

### ISSUE THREAD

**Issue by sbstnrss** [querqy/querqy-docs#5]
The "request parameters" link on https://docs.querqy.org/querqy/index.html points to https://docs.querqy.org/querqy/querqy-more-about-queries which is not working. Should be https://docs.querqy.org/querqy/more-about-queries.html.

![querqy_doc_broken_link](https://user-images.githubusercontent.com/74548034/99259480-5ed1ca80-281a-11eb-8d98-e76a3d4845d8.png)

**Comment by renekrie** [comment]
Thank you for reporting this! @sbstnrss
