### ISSUE TITLE
GET request for rewriter

### ISSUE THREAD

**Issue by ta-tang** [querqy/querqy-docs#6]
Hi everybody,
currently it's only possible to PUT and UPDATE a rewriter (incl. the rules). 
It'd be great to add a GET in order to actually see the configured rewriters (especially the rules that have been added to the rewriter). 

What do you guys think?

Thanks in advance!

**Comment by renekrie** [comment]
Yes, definitely. And it shouldn't be too hard to implement. @ta-tang, would you mind creating an issue in the https://github.com/querqy/querqy-elasticsearch repo?

Many thanks,
René

**Comment by ta-tang** [comment]
Sure! Sorry for the mistake. I'll close this issue.
